-- Enable UUID extension
create extension if not exists "uuid-ossp";

-- Users table (Independent Admin Authentication or linked to Supabase Auth)
-- For simplicity, we keep the structure but in a real Supabase app, we should link to auth.users
create table public.users (
  id bigint generated by default as identity primary key,
  name text not null,
  email text not null unique,
  email_verified_at timestamptz,
  is_admin boolean not null default false,
  password text not null, -- Will store hashed password if using custom auth, or ignore if using Supabase Auth
  two_factor_secret text,
  two_factor_recovery_codes text,
  two_factor_confirmed_at timestamptz,
  remember_token text,
  created_at timestamptz default now(),
  updated_at timestamptz default now()
);

-- UMKM Profiles
create table public.umkm_profiles (
  id bigint generated by default as identity primary key,
  name text not null,
  owner_name text not null,
  address text not null,
  phone text not null,
  email text,
  story text not null,
  established_year integer,
  logo_path text,
  created_at timestamptz default now(),
  updated_at timestamptz default now()
);

-- Products
create table public.products (
  id bigint generated by default as identity primary key,
  umkm_id bigint not null references public.umkm_profiles(id) on delete cascade,
  name text not null,
  description text not null,
  history text not null,
  philosophy text not null,
  video_path text,
  qr_code_path text,
  unique_code text not null unique,
  status text not null default 'active' check (status in ('active', 'inactive')),
  created_at timestamptz default now(),
  updated_at timestamptz default now()
);

-- Product Images
create table public.product_images (
  id bigint generated by default as identity primary key,
  product_id bigint not null references public.products(id) on delete cascade,
  image_path text not null,
  alt_text text,
  sort_order integer not null default 0,
  is_featured boolean not null default false,
  created_at timestamptz default now(),
  updated_at timestamptz default now()
);

-- QR Scans
create table public.qr_scans (
  id bigint generated by default as identity primary key,
  product_id bigint not null references public.products(id) on delete cascade,
  scanned_at timestamptz not null default now(),
  ip_address text,
  user_agent text,
  location_data jsonb,
  created_at timestamptz default now(),
  updated_at timestamptz default now()
);

-- Reviews
create table public.reviews (
  id bigint generated by default as identity primary key,
  product_id bigint not null references public.products(id) on delete cascade,
  customer_name text not null,
  rating integer not null check (rating >= 1 and rating <= 5),
  comment text not null,
  review_images jsonb,
  status text not null default 'pending' check (status in ('pending', 'approved', 'rejected')),
  created_at timestamptz default now(),
  updated_at timestamptz default now()
);

-- Row Level Security (RLS) Policies
-- Enable RLS on all tables
alter table public.users enable row level security;
alter table public.umkm_profiles enable row level security;
alter table public.products enable row level security;
alter table public.product_images enable row level security;
alter table public.qr_scans enable row level security;
alter table public.reviews enable row level security;

-- Policies
-- Public Read Access
create policy "Public profiles are viewable by everyone" on public.umkm_profiles for select using (true);
create policy "Public products are viewable by everyone" on public.products for select using (true);
create policy "Public product images are viewable by everyone" on public.product_images for select using (true);
create policy "Public reviews are viewable by everyone" on public.reviews for select using (status = 'approved');

-- Insert Access (Reviews and Scans)
create policy "Anyone can create reviews" on public.reviews for insert with check (true);
create policy "Anyone can create scans" on public.qr_scans for insert with check (true);

-- Admin Access (Authenticated Users have full access)
-- Products
create policy "Authenticated users can insert products" on public.products for insert to authenticated with check (true);
create policy "Authenticated users can update products" on public.products for update to authenticated using (true);
create policy "Authenticated users can delete products" on public.products for delete to authenticated using (true);

-- Product Images
create policy "Authenticated users can insert product images" on public.product_images for insert to authenticated with check (true);
create policy "Authenticated users can update product images" on public.product_images for update to authenticated using (true);
create policy "Authenticated users can delete product images" on public.product_images for delete to authenticated using (true);

-- UMKM Profiles
create policy "Authenticated users can insert UMKM" on public.umkm_profiles for insert to authenticated with check (true);
create policy "Authenticated users can update UMKM" on public.umkm_profiles for update to authenticated using (true);
create policy "Authenticated users can delete UMKM" on public.umkm_profiles for delete to authenticated using (true);

-- Reviews (Admin can update and delete)
create policy "Authenticated users can view all reviews" on public.reviews for select to authenticated using (true);
create policy "Authenticated users can update reviews" on public.reviews for update to authenticated using (true);
create policy "Authenticated users can delete reviews" on public.reviews for delete to authenticated using (true);

-- QR Scans
create policy "Authenticated users can view all scans" on public.qr_scans for select to authenticated using (true);
create policy "Authenticated users can delete scans" on public.qr_scans for delete to authenticated using (true);

-- Users
create policy "Authenticated users can view users" on public.users for select to authenticated using (true);
